### ISSUE TITLE
Support control for how events are aggregated/combined into compound events

### ISSUE THREAD

**Issue by juancq** [mmcdermott/EventStreamGPT#111]
There are times when I want events falling on the same timestamp to be combined, and other times where I would want them kept separate. Suppose I have the following, where admissions refers to hospital admissions, procedures have procedure dates associated with them, and procedures always occur in hospital admissions and never in emergency visits: 

```yaml
inputs: 
  subjects:
    ...
  admissions:
    input_df: 'admissions.parquet'
    ...
  emergency:
    input_df: 'emergency.parquet'
    ...
  procedures: # these only occur along with admission events
    input_df: 'procedures.parquet'
    ...

measurements: 
  ...
  dynamic:
    multi_label_classification: 
      admissions:
        - facility_type
        - acute_type
        ...
      emergency:
        - separation_code
        - triage_category
        ...
      procedure:
        - procedure_code
```

Suppose I have an admission event, emergency event, and a procedure event occurring on the same timestamp. How can I indicate that admission and procedure can be merged to a compound event (of type ADMISSION_PROCEDURE) but emergencies should be kept as a separate event? With my sequence of events ideally looking like:

event_type| date|... | blah
-- | -- | -- | --
u32 | datetime[μs] | ... | blah
...| 2010-03-15 00:00:00 |  | 
EMERGENCY| 2010-10-20 00:00:00 |  | 
ADMISSION_PROCEDURE| 2010-10-20 00:00:00 | |
