### ISSUE TITLE
Setting train_subset_size to float generates ValidationError

### ISSUE THREAD

**Issue by juancq** [mmcdermott/EventStreamGPT#52]
Using a float for the train_subset_size parameter in pretrain config yaml generates an error. 
```yaml
defaults:
  - pretrain_config
  - _self_

experiment_dir: "./testi"

data_config:
  save_dir: "sample_data/processed/sample"
  train_subset_size: 0.8
```
Error:
```sh
In 'pretrain_test': ValidationError raised while composing config:
Value '0.8' of type 'float' is incompatible with type hint 'Union[int, str]'
    full_key: data_config.train_subset_size
    reference_type=PytorchDatasetConfig
    object_type=PytorchDatasetConfig
```

The fix is to add float to: https://github.com/mmcdermott/EventStreamGPT/blob/0008ef47141f86eb496bc8db5a42701728e3f662/EventStream/data/config.py#L740-L740
