### ISSUE TITLE
Support same variable name across different input sources

### ISSUE THREAD

**Issue by juancq** [mmcdermott/EventStreamGPT#53]
I have the following input sources:

```yaml
inputs: 
  subjects:
    ...
  admissions:
    input_df: 'admissions.parquet'
    ...
  emergency:
    input_df: 'emergency.parquet'
    ...

measurements: 
  ...
  dynamic:
    multi_label_classification: 
      admissions:
        - facility_type
        - procedure
        ...
      emergency:
        - facility_type
        - triage_category
        ...
```

Getting the following error when running my build_dataset script: 
```bash
ValueError: facility_type differs across input sources. 
```

How can I have input sources with the same name (facility_type in admissions and in emergency)? Or how can I implement aliasing? i.e. something along the lines of: 

```yaml
...
measurements: 
  ...
  dynamic:
    multi_label_classification: 
      admissions:
        - facility_type
        - procedure
        ...
      emergency:
        - facility_type as ed_facility_type
        - triage_category
        ...
```
